### ISSUE TITLE
Planejamento da Avaliação do Protótipo de Alta Fidelidade

### ISSUE THREAD

**Issue by geraldovictor** [Interacao-Humano-Computador/2020.1-BCE#101]
### Descrição:
Uma vez feito o protótipo de alta fidelidade, é necessário avaliá-lo. Desse modo é preciso fazer um planejamento de como será feito essa avaliação, com quem, quando, etc.

O resultado dessa issue é um documento no modelo que estamos seguindo (introdução / objetivo / metodologia / desenvolvimento / conclusão / referência) detalhando aspectos relacionados ao processo de avaliação. 

### Critérios de aceitação:
- Deve haver uma tabela de versionamento
- Deve haver uma introdução
- Deve haver um tópico falando sobre o objetivo de se fazer um planejamento
- Deve haver um tópico falando sobre a metodologia de avaliação que será usada
- Deve haver o detalhamento da avaliação. 
- Deve haver referências bibliográficas

**Comment by durvalcarvalho** [comment]
Essa issue foi desmembrada nas seguintes issues:
- #117 Criar plano de avaliação do prot. de alta fidelidade referente a "Renovação do prazo de empréstimo" 
- #118 Criar plano de avaliação do prot. de alta fidelidade referente a "agendamento de empréstimo"
- #119 Criar plano de avaliação do prot. de alta fidelidade referente a "Busca de livro no acervo"
- #120 Criar plano de avaliação do prot. de alta fidelidade referente a "autentificação"
