### ISSUE TITLE
Criar slide de apresentação para PC1

### ISSUE THREAD

**Issue by RafaellaJunqueira** [Interacao-Humano-Computador/2020.1-BCE#13]
### Descrição:
Criar slide para a apresentação do Ponto de Controle 1.

### Critérios de aceitação:
- Esse documento deve conter um resumo do PC1

### Tarefas:
Checklist de ações que devem ser realizadas.

- [x] Equipe
- [x] Lista de sites avaliados
- [x] Planejamento do projeto
- [x] Cronograma de atividades

**Comment by isabellacgmsa** [comment]
Essa issue foi realocada para a sprint 2, já que sua conclusão depende de outras issues.
