### ISSUE TITLE
Definir as características da plataforma

### ISSUE THREAD

**Issue by RafaellaJunqueira** [Interacao-Humano-Computador/2020.1-BCE#45]
### Descrição:
Criar um documento que descreva as características da plataforma (site da BCE), suas possibilidades e limitações. Esse doc faz parte da análise de requisitos do ciclo de Mayhew. 

### Critérios de aceitação:
- Este documento deve conter tabela de versionamento
- Este documento deve conter bibliografia 

### Tarefas:
- [x] Objetivos
- [x] Restrições
- [x] Recursos

**Comment by durvalcarvalho** [comment]
Acredito que essa issue não tenha sido especificada como deveria. Características da plataforma se refere as características do computador/servidor que o sistema irá rodar, não ao sistema da BCE em si... O trabalho realizado pelo @durvalcarvalho pode ser utilizado na issue #63 (storyboard ), pois será necessário mapear as funcionalidades do sistema, trabalho esse que o @joao15victor08 já fez.

![image](https://user-images.githubusercontent.com/31013187/94468342-a1701280-019a-11eb-8b4e-0abf25f94a76.png)
![image](https://user-images.githubusercontent.com/31013187/94468401-bc428700-019a-11eb-895f-6d50690408e9.png)
