### ISSUE TITLE
Consertar imagens

### ISSUE THREAD

**Issue by RafaellaJunqueira** [Interacao-Humano-Computador/2020.1-BCE#46]
### Descrição:
Consertar o caminho das imagens para que não quebrem nem na visualização dos documentos individuais nem no github pages.

### Critérios de aceitação:
- Funcionar no Github Pages
- Funcionar no Github

**Comment by durvalcarvalho** [comment]
A solução que propus inicialmente não soluciona todos os links de imagens. Após o merge percebi que algumas imagens continuavam quebrando.... Isso de deve ao fato que o nosso site está hospedado na suburl `https://github.com/Interacao-Humano-Computador/2020.1-BCE`, pois quando as imagens são configuradas para aparecer no markdown(com o caminho absoluto), o markdown é compilado para HTML e o link aponta para a url `https://github.com/Interacao-Humano-Computador/`

Eu sugiro que continuemos fazendo os documentos para visualização somente pelo Github Pages
