### ISSUE TITLE
Utilizar o modelo de relatório consolidado para as avaliações heurística

### ISSUE THREAD

**Issue by durvalcarvalho** [Interacao-Humano-Computador/2020.1-BCE#58]
### Descrição:
Atualmente a avaliação dos sites pré-avaliados foram feitas em texto corrido. O professor sugeriu que essa avaliação utilizasse o modelo consolidado de relatório. 

### Critérios de aceitação:
- Para cada site deve haver um tabela de avaliação

### Tarefas:
- [x]  Encontrar o relatório consolidado

**Comment by RafaellaJunqueira** [comment]
Documento da Rafa sobre avaliação heurística do site SPTrans https://drive.google.com/file/d/1hoI_oeGrFlz-IpDirZ8zkfTA9yEL_TRs/view?usp=sharing

**Comment by durvalcarvalho** [comment]
Quando fiz a avaliação do site da BCE (a entrega do trabalho individual) eu não usei as heurísticas de Nielsen. Eu realizei entrevistas com amigos que já usaram o serviço e os resultados estão presentes nos seguintes documentos.

[Planejamento da avaliação](https://github.com/Interacao-Humano-Computador/2020.1-BCE/files/5293700/PlojetoParteIndividualPlanejAvalicaoDurvalCarvalhoDeSouza.pdf)

[Execução da avaliação](https://github.com/Interacao-Humano-Computador/2020.1-BCE/files/5293699/PlojetoParteIndividualMetodoeAvalicaoDurvalCarvalhoDeSouza.pdf)

**Comment by geraldovictor** [comment]
Meu documento da avaliação heurística do site do SAE
https://drive.google.com/file/d/16RBbiINW4fbwLSiFrG4A-cibhwpcnjY5/view?usp=sharing
