### ISSUE TITLE
Gravar editar e subir vídeo da apresentação

### ISSUE THREAD

**Issue by geraldovictor** [Interacao-Humano-Computador/2020.1-BCE#62]
### Descrição:
Fazer a gravação da apresentação e fazer cortes necessários no vídeo e subir ele no youtube e disponibilizar link.

Nesse vídeo deve está presente:
- Perfil usuário
- Personas 
- Análise de tarefas

### Critérios de aceitação:
- Todos os integrantes devem participar do vídeo
- O vídeo não deve durar mais de 10 minutos
- Todos os tópicos listados acima devem está presente no vídeo
- O vídeo deve está pronto até o dia 05/10/2020
- O vídeo precisa ser aprovado por todos após a disponibilização do link.

 ### Tarefas:
- [x] Combinar um dia para todos participarem da gravação
- [x] Gravar apresentação
- [x] Editar o vídeo da apresentação
- [x] Subir o vídeo da apresentação para o youtube

**Comment by geraldovictor** [comment]
Renião marcada para o dia 02/10 de 18-20. Todos concordaram com esse horário de acordo com enquete feita no telegram.

**Comment by durvalcarvalho** [comment]
Só lamento pelos outros grupos. Temos um youtuber no nosso 😂 
![BlankDemandingAzurevasesponge-max-1mb](https://user-images.githubusercontent.com/31013187/95078074-f0fa9500-06ea-11eb-8c58-14d0d8b12f76.gif)
