### ISSUE TITLE
Iniciar criação do storyboard

### ISSUE THREAD

**Issue by RafaellaJunqueira** [Interacao-Humano-Computador/2020.1-BCE#63]
### Descrição:
Deve-se iniciar a criação do storyboard, as ideias principais e a ferramenta utilizada.

### Tarefas:
- [x] Definir ferramenta para utilizar
- [x] Definir ideias principais 
- [ ] Incluir storyboard dos dois objetivos: agendamento de empréstimo (reservar livro) e renovar prazo de devolução

**Comment by durvalcarvalho** [comment]
O seguinte trecho foi retirado do documento produzido pelo @joao15victor08 referente a issue #45. O conteúdo, por mais que não faça referência as características da plataforma, é de grande utilidade para essa issue, pois mapeia as funcionalidades do sistema da BCE.

```
## 3. Recursos
* Realizar a reserva de um material;
* Consultar situação de reservas;
* Cancelar reservas de material;
* Ver o histórico de reservas;
* Renovar prazo de devolução;
* Ver o histórico de renovações realizadas;
* Ver débitos pendentes com a BCE;
* Ver o histórico de débitos;
* Ver o histórico de materiais pendentes.


## 4. Restrições
* O site não é responsivo para dispositivos móveis.
* Não possui método de pagamento online dos débitos.
```
