### ISSUE TITLE
Relato do andamento da sprint 4 (semelhante a daily)

### ISSUE THREAD

**Issue by durvalcarvalho** [Interacao-Humano-Computador/2020.1-BCE#68]
### Descrição:
Essa semana os integrantes do grupo não conseguiram se reunir por video chamada para discutir o andamento da sprint. Desse modo foi decido que os participantes da sprint 4 iriam relatar o status da sprint por texto. 

### Critérios de aceitação:
- No relato deve descrever o que foi feito.
- No relato deve descrever o que pretende fazer.
- No relato deve conter as dificuldades encontradas, caso exista.

**Comment by isabellacgmsa** [comment]
**O que foi feito**: Em relação à issue de iniciar o StoryBoard (#63) eu já fiz toda a parte teórica do documento e conversei com o Geraldo sobre as histórias que iríamos descrever.
**O que pretendo fazer**: Vou revisar a parte teórica antes de finalizar a sprint.

**Comment by durvalcarvalho** [comment]
**O que foi feito**: Eu adicionei legendas em todas as imagens e tabelas dos documentos que estavam presentes da master até o dia 29 de setembro. Também redimensionei as imagens que estavam com problemas de tamanho em sua exibição. Eu investiguei o problema de linkagem das imagens do github e github pages, conclui que é melhor manter o suporte somente ao github pages, pois caso contrário iriámos limitar a estilização (tamanho, posição na tela, inserção de bordas) das imagens caso alterasse o transpilador de markdown do docsify (explico isso com detalhe na issue #46)

**O que pretendo fazer:** Hoje pretendo trabalhar nos slides.

**Dificuldades**: Estou bastante atribulado devido as outras matérias, não estou podendo dar muito suporte ao grupo, porém o grupo vem se mostrando auto-organizável.

**Comment by RafaellaJunqueira** [comment]
**O que foi feito:** inseri a ferramenta utilizada para fazer os diagramas da análise de tarefas, reorganizei o documento "Análise de tarefas", inseri os avaliações dos sites feitos ao final do documento "Escolha dos sites" e criei a parte dos slides tmb referente à análise de tarefas para o PC2.

**O que pretendo fazer**: só gravar o vídeo para o PC2 hoje.

**Dificuldades:** listas, simulados e provas de outras matérias.

**Comment by geraldovictor** [comment]
**O que foi feito:** As issues de bug designadas a mim e combinei o horário de gravação da apresentação

**O que pretendo fazer**: gravar, editar e subir a apresentação, colocar minha parte no slide de apresentação e criar roteiro de conversa para storyboard amanhã.

**Dificuldades:** listas e provas de outras matérias.

**Comment by joao15victor08** [comment]
O que foi feito: Atualizei o cronograma, e trabalhei na issue de características da plataforma.

O que pretendo fazer: Terminar minhas issues atrasadas de metas de usabilidade, e características da plataforma.

Dificuldades: Essa semana tive provas de outras matérias. e uma dificuldade particular em entender como definir as características da plataforma
