### ISSUE TITLE
Planejamento e avaliação - usuários

### ISSUE THREAD

**Issue by RafaellaJunqueira** [Interacao-Humano-Computador/2020.1-BCE#69]
### Descrição:
Criar um planejamento para avaliação de perfil de usuários e, posteriormente, realizar e documentar a avaliação de perfil.

### Critérios de aceitação:
- Este documento deve conter referências bibliográficas
- Este documento deve conter tabela de versionamento
- Deve ser realizado um questionário (forms) 

### Tarefas:
- [x] Criar documento de planejamento (@isabellacgmsa, @geraldovictor)
- [x] Criar um questionário (@RafaellaJunqueira, @durvalcarvalho, @geraldovictor, @joao15victor08)
- [x] Divulgar o questionário (Todos)
- [x] Analisar resultados (@durvalcarvalho @RafaellaJunqueira )
- [x] Atualizar os documentos (perfil_de_usuario.md) (@durvalcarvalho)
- [x] Atualizar os slides (@durvalcarvalho @geraldovictor)
- [x] Gravar a apresentação (@geraldovictor)

**Comment by joao15victor08** [comment]
Quando você acessa os sistemas da BCE, você utiliza quais desses dispositivos?
- [ ] Celular
- [ ] Notebook pessoal
- [ ] Computador pessoal
- [ ] tablet pessoal
- [ ] Notebook da BCE
- [ ] Computador da BCE

**Comment by geraldovictor** [comment]
Qual é a área do conhecimento so seu curso?
- [ ] Humanas 
- [ ] Exatas
- [ ] Biológicas
- [ ] Tecnológicas

**Comment by durvalcarvalho** [comment]
(e.g., cargo, função, experiência, nível de instrução, atividades principais, faixa etária etc.)

**Comment by durvalcarvalho** [comment]
experiência (leigo/novato, especialista);

**Comment by durvalcarvalho** [comment]
> Frequência de uso de tecnologia do sistema:
>> [5] Constante: várias vezes por semana
>>[4] Alta: semanalmente
>>[3] Média: Mensalmente
>>[2] Ocasional: Semestralmente
>>[1] Baixa: Anualmente ou Nunca

**Comment by geraldovictor** [comment]
Quais serviços da BCE que você mais utiliza (mais de uma alternativa)?
* Empréstimo 
* Ambiente de estudo
* Utilização dos computadores para estudo
* Consulta de acervo físico para referências bibliográficas
* Consulta de acervo digital para referências bibliográficas
* Outros

**Comment by durvalcarvalho** [comment]
![tenor (1)](https://user-images.githubusercontent.com/31013187/95077691-4c785300-06ea-11eb-9178-6811e28750f2.gif)
