### ISSUE TITLE
Realizar Avaliação Heurística

### ISSUE THREAD

**Issue by durvalcarvalho** [Interacao-Humano-Computador/2020.1-BCE#7]
### Descrição:
Realizar e documentar a avaliação heurística do site da BCE.

### Critérios de aceitação:
- Esse documento deve conter tabela de versionamento
- Esse documento deve conter as referências bibliográficas
- Deve-se utilizar o modelo de relatório consolidado 

### Tarefas:
- [ ] Analisar os guias de estilo dos projetos dos semestres passados
- [ ] Definir quais partes do site será avaliado
- [ ] Dividir as partes entre os avaliadores
- [ ] Realizar avaliação
- [ ] Documentar avaliação

**Comment by durvalcarvalho** [comment]
O seguinte artigo se trata de uma avaliação de usabilidade realizada no site da BCE.
[Avaliação_de_usabilidade_de_websitesintegrando_gestores,_desenvolvedores_e_usuários.pdf](https://github.com/Interacao-Humano-Computador/2020.1-BCE/files/5227133/6.perfect.avaliacao_de_usabilidade_de_websitesintegrando_gestores._desenvolvedores_e_usuarios.pdf)

**Comment by durvalcarvalho** [comment]
O seguinte documento será de grande serventia para essa issue:
[AVALIAÇÃO DA INTERFACE DO SITE DA BIBLIOTECA DO UNIPROJEÇÃO: USABILIDADE E ACESSIBILIDADE COMO FATORES DE MELHORIA.pdf](https://github.com/Interacao-Humano-Computador/2020.1-BCE/files/5232594/AVALIACAO.DA.INTERFACE.DO.SITE.DA.BIBLIOTECA.DO.UNIPROJECAO.USABILIDADE.E.ACESSIBILIDADE.COMO.FATORES.DE.MELHORIA.pdf)

Nele é analisado o site da biblioteca do UniProjeção. Esse site usa o mesmo sistema da BCE, o pergamum
![image](https://user-images.githubusercontent.com/31013187/93347409-69b4b280-f80b-11ea-880a-a12ee8601c38.png)

![image](https://user-images.githubusercontent.com/31013187/93347432-70dbc080-f80b-11ea-876f-797966d90165.png)

**Comment by isabellacgmsa** [comment]
O arquivo a seguir trata da avaliação do site da ZARA:
[Avaliação ZARA.pdf](https://drive.google.com/file/d/1gPyruKWuxlbXshpvvpbHeHFyPaRf0TOZ/view?usp=sharing)

**Comment by RafaellaJunqueira** [comment]
Acho que podemos repensar a necessidade dessa issue.
