### ISSUE TITLE
Criar slide do PC3

### ISSUE THREAD

**Issue by isabellacgmsa** [Interacao-Humano-Computador/2020.1-BCE#80]
### Descrição:
Criar os slides para a apresentação do ponto de controle 3

### Critérios de aceitação:
Deve conter um resumo do PC3

### Tarefas:
Checklist de ações que devem ser realizadas.

- [x]  Metas de Usabilidade
- [ ]  Guias de Estilo
- [x]  Princípios Gerais de Projeto

**Comment by durvalcarvalho** [comment]
[Link dos slides que iremos modificar](https://docs.google.com/presentation/d/12PmY1RN2heY94v4jHU-6V3aaA1SKZQHw0MrgZu-nFTs/edit?usp=sharing)
