### ISSUE TITLE
Criar protótipo de alta fidelidade

### ISSUE THREAD

**Issue by durvalcarvalho** [Interacao-Humano-Computador/2020.1-BCE#84]
### Descrição:
Com base no protótipo de baixa fidelidade consolidado, é desejável que se crie uma versão de maior fidelidade com o design final, com o uso de ferramentas computacionais de prototipagem. Uma vez com o protótipo de alta fidelidade finalizado, é sugerível utilizá-lo em uma entrevista com o usuário, para assim validar os fluxos de uso pensados.

### Critérios de aceitação:
- Deve ser uma versão melhorada do protótipo de baixa fidelidade
- Deve seguir o guia de estilo definido
- Deve explicar o que é protótipo de alta fidelidade, e sua importância

### Tarefas:
- [ ] Analisar o protótipo de baixa fidelidade
- [ ] Analisar o guia de estilo
- [ ] Analisar qual a melhor ferramenta para prototipagem (de preferência uma colaborativa)

**Comment by geraldovictor** [comment]
Essa issue foi desmembrada em quatro issues sendo elas: 
#113 Criar protótipo de alta fidelidade de autentificação
#114 Criar protótipo de alta fidelidade de agendamento de empréstimo
#115 Criar protótipo de alta fidelidade - Renovação do prazo de empréstimo
#116 Criar protótipo de alta fidelidade da tarefa de Busca de livro no acervo
