### ISSUE TITLE
Documentação da 8ª Sprint

### ISSUE THREAD

**Issue by geraldovictor** [Interacao-Humano-Computador/2020.1-BCE#99]
## Documentação da 8ª Sprint

Descrição | Data
--------- | ------
| **Data de início**   | 27 de outubro |
| **Data de término** | 03 de novembro |

| Issue | Responsável | Concluída | Causa |
| :-:   | :-:         | :-:       | :-:   | 
| ⚠️ #97 Gravar editar e subir vídeo da apresentação PC4 | @geraldovictor  | ✔️ ||
| #100 Validação (avaliação) do Protótipo de Baixa Fidelidade (Papel) | @durvalcarvalho @isabellacgmsa | ✔️ |
| #95 Validação (avaliação) do storyboard | @geraldovictor @joao15victor08 @RafaellaJunqueira  |✔️ |
| ⚠️ #105 Criar os slides do ponto de controle 4 | @geraldovictor @isabellacgmsa @durvalcarvalho @joao15victor08 @RafaellaJunqueira  | ✔️ |

**Comment by durvalcarvalho** [comment]
https://docs.google.com/presentation/d/16lqxZNgGmQrrCiV4XHqffSyM4q9Nm0VbLBxHz7LfoAc/edit?usp=sharing

**Comment by durvalcarvalho** [comment]
Link para edição dos slides
https://docs.google.com/presentation/d/16lqxZNgGmQrrCiV4XHqffSyM4q9Nm0VbLBxHz7LfoAc/edit?usp=sharing
